pharmafind/pharmafind/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import account_redirect, home_view, pharmamanage, tohome, search, drugview
from testapp.views import testview
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('home/', tohome, name='home'),
    path('search/', search, name='search'),
    path('test/', testview, name='test'),
    path('login/', LoginView.as_view()),
    path('accounts/', include("django.contrib.auth.urls")),
    path('medicineview/', drugview, name='medicineview'),
    path('pharmamanage/', pharmamanage, name='pharmamanage'),
    path('accounts/profile/', account_redirect, name='account-redirect')
]

pharmafind/pages/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class PharmacyManager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user.username

pharmafind/pharmacydatabase/models.py
from operator import mod
from statistics import mode
from tkinter import CASCADE
from django.db import models
from matplotlib import mlab
from pages.models import PharmacyManager

# Create your models here.
class Brand(models.Model):
    name = models.CharField(max_length=50, primary_key=True)

    def __str__(self):
        return self.name

class DrugType(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Drug(models.Model):
    name = models.CharField(max_length=50, default="")
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    drugtype = models.ForeignKey(DrugType, on_delete=models.CASCADE)
    milligrams = models.FloatField(blank=True, null=True)

    def __str__(self):
        if str(self.brand) == "No brand":
            return self.drugtype.name + " with no brand, and a strength of " + str(self.milligrams) + "mg"
        else:
            return self.drugtype.name + " of brand " + self.brand.name + " with a strength of " + str(self.milligrams) + "mg"

class Pharmacy(models.Model):
    name = models.CharField(max_length=100)
    adress = models.CharField(max_length=100)
    phone = models.CharField(max_length=15, blank=True, null= True)
    contactemail = models.EmailField(max_length=50, blank=True, null= True)
    website = models.CharField(max_length=50, blank=True, null= True)
    delivery = models.BooleanField()
    canimport = models.BooleanField()
    country = models.CharField(max_length=50, default="")
    area = models.CharField(max_length=50, default="")
    city = models.CharField(max_length=50, default="")
    gmaplink = models.CharField(max_length=300, default='https://maps.google.com')
    pharmacymanager = models.ForeignKey(PharmacyManager, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(s):
        if "pharmacy" in s.name.lower():
            return s.name
        else:
            return s.name + "Pharmacy"

class DrugSet(models.Model):
    drug = models.ForeignKey(Drug, on_delete=models.CASCADE)
    count = models.PositiveIntegerField()
    pharmacy = models.ForeignKey(Pharmacy, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.count) + ' x "' + str(self.drug) + '", (in  pharmacy "' + self.pharmacy.name +'")'


pharmafind/testapp/models.py
from django.db import models

# Create your models here.

pharmafind/pages/forms.py
from django import forms
from django.utils.safestring import mark_safe

class SearchForm(forms.Form):
    query = forms.CharField(label='', max_length=500, widget=forms.TextInput(attrs={'size':40, 'class':"searchbox"}))
    weight = forms.FloatField(label=mark_safe('<br><br>Strength (mg)'), required=False)
    country = forms.CharField(label=mark_safe("<br><br>Country:"), max_length=50, initial="Sri Lanka")
    area = forms.CharField(label=mark_safe("Area:"), max_length=50, initial="Colombo")

pharmafind/pages/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .forms import SearchForm
from pharmacydatabase.models import Drug, DrugSet, DrugType, Brand, Pharmacy

home = 'http://127.0.0.1:8000'

# Create your views here.
def home_view(request):
    query = request.GET.get('query', -1)
    weight = request.GET.get('weight', False)
    area = request.GET.get('area', False)
    if query != -1:
        form = SearchForm(request.GET)
        if form.is_valid():
            redirectto = '/search/?query=' + query
            if weight:
                redirectto += '&weight=' + weight
            if area:
                redirectto += '&area=' + area
            return redirect(redirectto)
    else:
        form = SearchForm()
    return render(request, "home.html", {'form':form})

def tohome(request):
    return redirect(home)

def search(request):
    query = request.GET.get('query', -1)
    weight = request.GET.get('weight', False)
    area = request.GET.get('area', False)
    form = SearchForm()
    if query == -1:
        return redirect(home)
    drugsets = DrugSet.objects.filter(drug__drugtype__name__contains=query)
    drugsets2 = DrugSet.objects.filter(drug__brand__name__contains=query)
    if weight:
        drugsets = drugsets.filter(drug__milligrams__contains=weight)
        drugsets2 = drugsets2.filter(drug__milligrams__contains=weight)
    if area:
        drugsets = drugsets.filter(pharmacy__area__contains=area)
        drugsets2 = drugsets2.filter(pharmacy__area__contains=area)
    drugsets = drugsets.union(drugsets2)
    drugsets = drugsets.order_by('-count', 'id')
    hasresults = drugsets.exists()
    return render(request, "search.html", {'query':query, 'weight':weight, 'form':form, 'results':drugsets, 'hasresults':hasresults, 'area':area})

def drugview(request):
    id = request.GET.get('id', False)
    if id:
        try:
            drugset = DrugSet.objects.get(pk=id)
        except:
            return render(request, "medicineviewerror.html")
        return render(request, "medicineview.html", {'drugset':drugset})
    else:
        return redirect(home)

def pharmamanage(request):
    currentuser = request.user
    if currentuser.is_authenticated:
        return render(request, "pharmamanage.html")
    else:
        return redirect(home + '/login/')

@login_required
def account_redirect(request):
    return redirect(home)

pharmafind/pharmacydatabase/views.py
from django.shortcuts import render

# Create your views here.

pharmafind/testapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponse
from pharmacydatabase.models import Brand, DrugType, Drug, DrugSet, Pharmacy

# Create your views here.

def testview(request):
    panadol = DrugType(name="panadol")
    panadol.save()
    return HttpResponse('This is a test page')

pharmafind/pages/templates/home.html
<html>
    <head>
        <title>PharmaFind | Home</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'home.css' %}">
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">
    </head>
    <body>
        <div id="topbar2">
            {% if user.is_authenticated %}
                {% if user.pharmacymanager %}
                    <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{%url 'pharmamanage' %}">Manage pharmacies</a>&emsp;<a href="{% url 'logout' %}">Logout</a></p>
                {% else %}
                    <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{% url 'logout' %}">Logout</a></p>
                {% endif %}
            {% else %}
                <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{% url 'login' %}">Login</a></p>
            {% endif %}
            <p align="left" id="version"><small><small>Version 1.0.0 (Prototype)</small></p>
        </div>
        <div id="intro">
            <h1 align="center"><br>{% load static %}<img src="{% static 'favicon128.png' %}"><br>Pharmafind<br></h1>
            <h3 align="center">Find your medicines, fast<br><br><br></h3>
        </div>
        <h2 class="pink" align="center">What medicine do you need?</h2>
        <h4 class="purple" align="center">NOTE: Please only enter one of the generic drug name and the brand name, our search engine does not support multiple words yet.</h4>
        <form align="center">
            {% csrf_token %}
            {{form}}
            <br>
            <br>
            <input type="submit" value="Search" class="searchbutton">
        </form>
        <p align="right" class="white">By Im-Pra Net (Praveen Athauda-Arachchi and Imadh Mashoor</p>
    </body>
</html>

pharmafind/pages/templates/medicineview.html
<html>
    <head>
        <title>PharmaFind | {{drugset.drug}} at "{{drugset.pharmacy}}"</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'home.css' %}">
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">
    </head>
    <body>
        <div id="topbar">
            {% if user.is_authenticated %}
                {% if user.pharmacymanager %}
                    <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{%url 'pharmamanage' %}">Manage pharmacies</a>&emsp;<a href="{% url 'logout' %}">Logout</a></p>
                {% else %}
                    <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{% url 'logout' %}">Logout</a></p>
                {% endif %}
            {% else %}
                <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{% url 'login' %}">Login</a></p>
            {% endif %}
            <h3 align="center" class="white"> {% load static %}<img src="{% static 'favicon32.png' %}">Pharmafind</h3>
            <p align="left" id="version"><small><small>Version 1.0.0 (Prototype)</small></p>
        </div>
        <h1 class="white">Medicine: {{drugset.drug}}</h1>

        <h2 class="pink">Pharmacy: {{drugset.pharmacy}}</h2>

        {% if drugset.count != 0 %}
            <h2 class="pink">{{drugset.count}} in stock</h2>
        {% else %}
            <h1 class="important">Out of stock</h1>
            <h2 class="pink">Restocking Date: 28.7.2022</h2>
        {% endif %}

        <h2 class="pink">Adress: {{drugset.pharmacy.adress}}</h2>

        {% if drugset.pharmacy.phone %}
        <h3 class="pink">Phone number: {{drugset.pharmacy.phone}}</h3>
        {% else %}
        <h3 class="greypink">Phone number not available</h3>
        {% endif %}

        {% if drugset.pharmacy.contactemail %}
        <h3 class="pink">Email: {{drugset.pharmacy.contactemail}}</h3>
        <h4><a href="mailto:{{drugset.pharmacy.contactemail}}" target="_blank" class="purple">Send e-mail</a></h4>
        {% else %}
        <h3 class="greypink">Email not available</h3>
        {% endif %}
        
        {% if drugset.pharmacy.website %}
        <h3 class="pink">Website: <a href="{{drugset.pharmacy.website}}" target="_blank" class="purple">{{drugset.pharmacy.website}}</a></h3>
        {% else %}
        <h3 class="greypink">Website not available</h3>
        {% endif %}

        {% if drugset.pharmacy.delivery %}
        <h4 class="pink">Delivery available</h4>
        {% else %}
        <h4 class="greypink">Delivery not available</h4>
        {% endif %}

        {% if drugset.pharmacy.canimport %}
        <h4 class="pink">Can import more</h4>
        {% else %}
        <h4 class="greypink">Cannot import more</h4>
        {% endif %}

        <h3 class="pink">Country: {{drugset.pharmacy.country}}<br>Area: {{drugset.pharmacy.area}}</h3>

        <h2><a href="{{drugset.pharmacy.gmaplink}}" target="_blank" class="purple">View pharmacy on Google Maps </a></h2>
    </body>
</html>

pharmafind/pages/templates/medicineviewerror.html
<html>
    <head>
        <title>PharmaFind | Error</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'home.css' %}">
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">
    </head>
    <body>
        <div id="topbar">
            {% if user.is_authenticated %}
                {% if user.pharmacymanager %}
                    <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{%url 'pharmamanage' %}">Manage pharmacies</a>&emsp;<a href="{% url 'logout' %}">Logout</a></p>
                {% else %}
                    <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{% url 'logout' %}">Logout</a></p>
                {% endif %}
            {% else %}
                <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{% url 'login' %}">Login</a></p>
            {% endif %}
            <h3 align="center" class="white"> {% load static %}<img src="{% static 'favicon32.png' %}">Pharmafind</h3>
            <p align="left" id="version"><small><small>Version 1.0.0 (Prototype)</small></p>
        </div>
        <h1 class="important">There was an error when trying to view medicine data</h1>
        <h2 class="important"><a href="javascript:history.back()">Back to previous page</a></h2>
    </body>
</html>

pharmafind/pages/templates/pharmamanage.html
<html>
    <head>
        <title>PharmaFind | Manage pharmacies</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'home.css' %}">
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">
    </head>
    <body>
        <div id="topbar">
            {% if user.is_authenticated %}
                {% if user.pharmacymanager %}
                    <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{%url 'pharmamanage' %}">Manage pharmacies</a>&emsp;<a href="{% url 'logout' %}">Logout</a></p>
                {% else %}
                    <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{% url 'logout' %}">Logout</a></p>
                {% endif %}
            {% else %}
                <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{% url 'login' %}">Login</a></p>
            {% endif %}
            <h3 align="center" class="white"> {% load static %}<img src="{% static 'favicon32.png' %}">Pharmafind</h3>
            <p align="left" id="version"><small><small>Version 1.0.0 (Prototype)</small></p>
        </div>
        {% if user.pharmacymanager %}
            <h2 class="white">Manage your pharmacies</h2>
            <h4 class="important">NOTE: The settings will only be added in a later version when pharmacies actually register with our app.</h4>
            {% for pharmacy in user.pharmacymanager.pharmacy_set.all %}
                <button type="button" class="collapsible" id="coll">{{pharmacy}}</button>
                <div class="content">
                    {% for drugset in pharmacy.drugset_set.all %}
                    <button type="button" class="collapsible" id="coll2">{{drugset}}</button>
                    <div class="content2">
                        <p class="white">This setting is incomplete and will be added in later versions.</p>
                    </div>
                    <br><br>
                    {% endfor %}
                </div>
                <br><br>
            {% endfor %}
        {% else %}
            <h2 class="important">Error: You are not a pharmacy manager.</h2>
            <h3 class="white"><a href="{% url 'home' %}">Back to home page</a></h3>
        {% endif %}
        <script>
            var coll = document.getElementsByClassName("collapsible");
            var i;

            for (i = 0; i < coll.length; i++) {
            coll[i].addEventListener("click", function() {
                this.classList.toggle("active");
                var content = this.nextElementSibling;
                if (content.style.display === "block") {
                content.style.display = "none";
                } else {
                content.style.display = "block";
                }
            });
            }
        </script>
    </body>
</html>

pharmafind/pages/templates/search.html
<html>
    <head>
        <title>PharmaFind | Search | "{{query}}"</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'home.css' %}">
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.png' %}">
    </head>
    <body>
        <div id="topbar">
            {% if user.is_authenticated %}
                {% if user.pharmacymanager %}
                    <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{%url 'pharmamanage' %}">Manage pharmacies</a>&emsp;<a href="{% url 'logout' %}">Logout</a></p>
                {% else %}
                    <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{% url 'logout' %}">Logout</a></p>
                {% endif %}
            {% else %}
                <p align="right" class="links"><a href="{% url 'home' %}">Home</a>&emsp;Sign up&emsp;<a href="{% url 'login' %}">Login</a></p>
            {% endif %}
            <h3 align="center" class="white"> {% load static %}<img src="{% static 'favicon32.png' %}">Pharmafind</h3>
            <p align="left" id="version"><small><small>Version 1.0.0 (Prototype)</small></p>
        </div>
        <form align="center">
            {% csrf_token %}
            {{form}}
            <br>
            <br>
            <input type="submit" value="Search" class="searchbutton">
        </form>
        {% if area %}
            {% if weight %}
                <h3 class="white">You searched for "{{query}}" with a strength of {{weight}}mg in {{area}}.</h2>
            {% else %}
                <h3 class="white">You searched for "{{query}}" with any strength in {{area}}.</h2>
            {% endif %}
        {% else %}
            {% if weight %}
                <h3 class="white">You searched for "{{query}}" with a strength of {{weight}}mg.</h2>
            {% else %}
                <h3 class="white">You searched for "{{query}}" with any strength.</h2>
            {% endif %}
        {% endif %}
        <br><br>
        {% if hasresults %}
            {% for drugset in results %}
                <a href="{% url 'medicineview' %}?id={{drugset.id}}" style="text-decoration:none">
                    <div class="pharmacy">
                        <h4 class="white">{{drugset.pharmacy}}</h4>
                        <h5 class="white">Has {{drugset.drug}}</h5>
                        {% if drugset.count != 0 %}
                            <h5 class="white">{{drugset.count}} in stock</h5>
                        {% else %}
                            <h4  class="important">Out of stock</h4>
                        {% endif %}
                    </div>
                </a>
                <br><br>
            {% endfor %}
        {% else %}
        <h2 class="important" align="center">No results found.</h2>
        <p class="pink" align="center">Please check the spelling of the search.<br><br>Also please note that our search engine does not support multiple words<br>yet, so please enter only one of the generic drug name and the brand.</p>
        {% endif %}
    </body>
</html>